In [2]:
#int
var = 100
var1 = var
print(id(var))
print(id(var1))
print(var is var1)

140723302752136
140723302752136
True


In [1]:
#float
car = 200.10
car1 = 200.10
car2 = 200.10
print(id(car))
print(id(car1))
print(id(car2))

2177764890672
2177765721168
2177765725104


In [2]:
#int
x = 100
print("id of x: ",id(x))

y = 100
print("id of y: ",id(y))

z = y
print("id of z: ",id(z))

id of x:  140731274747784
id of y:  140731274747784
id of z:  140731274747784


In [11]:
#float
x = 100.10
print("id of x: ",id(x))

y = 100.10
print("id of y: ",id(y))

z = y
print("id of z: ",id(z))

id of x:  1685765357008
id of y:  1685765356528
id of z:  1685765356528


In [6]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print("Original Array:")
print(arr)

# Perform some basic operations
mean = np.mean(arr)
sum_val = np.sum(arr)
max_val = np.max(arr)
min_val = np.min(arr)

# Print the results
print("\nMean:", mean)
print("Sum:", sum_val)
print("Maximum:", max_val)
print("Minimum:", min_val)

# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the 2D array
print("\n2D Array:")
print(matrix)

# Transpose the 2D array
transposed_matrix = np.transpose(matrix)

# Print the transposed array
print("\nTransposed 2D Array:")
print(transposed_matrix)


Original Array:
[1 2 3 4 5]

Mean: 3.0
Sum: 15
Maximum: 5
Minimum: 1

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed 2D Array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
